name: Build and Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'

    - name: Cache front-end dependencies
      uses: actions/cache@v3
      with:
        path: front-end/node_modules
        key: ${{ runner.os }}-front-end-${{ hashFiles('front-end/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-front-end-

    - name: Cache root dependencies
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-root-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-root-

    - name: Install and Build front-end
      run: |
        cd front-end
        npm ci
        npm run build
      env:
        CI: true

    - name: Install and Build server
      run: |
        npm ci
        npm run build
        mv index ./front-end/build/network-rc

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/master'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./front-end/build
